### ISSUE TITLE
No files after opening fileclass view with command palette

### ISSUE THREAD

**Issue by Asetnozama** [mdelobelle/metadatamenu#187]
Loving the new "3 tab" fileclass view from the latest update. But on windows opening the view through the command palette doesn't show any files in the table view. 
It does work with the right click menu on a file

**Comment by mdelobelle** [comment]
Hi thank you for the report. Do you have any error message in the console?

**Comment by Asetnozama** [comment]
Do you mean this??::


Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'api')
    at eval (plugin:metadata-menu:12004:30)
    at Array.forEach (<anonymous>)
    at FieldIndex.getFilesFieldsExists (plugin:metadata-menu:12003:17)
    at FieldIndex.eval (plugin:metadata-menu:11766:12)
    at Generator.next (<anonymous>)
    at eval (plugin:metadata-menu:60:61)
    at new Promise (<anonymous>)
    at __async (plugin:metadata-menu:44:10)
    at FieldIndex.fullIndex (plugin:metadata-menu:11755:12)
    at FieldIndex.eval (plugin:metadata-menu:11714:22)
plugin:dataview:13951 Dataview: all 448 files have been indexed in 0.153s (448 cached, 0 skipped).
app.js:1 Allow attribute will take precedence over 'allowfullscreen'.
2
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at Nl.handlecMenuToolbar (plugin:editing-toolbar:28:87803)
    at t.e.tryTrigger (app.js:1:1027924)
    at t.e.trigger (app.js:1:1027857)
    at t.trigger (app.js:1:1648741)
    at t.activeLeafEvents (app.js:1:1634569)
    at s (app.js:1:692224)
    at l (app.js:1:692330)

**Comment by mdelobelle** [comment]
It looks like metadata menu has tried to launch before dataview.
Could you "disable" then "enable" metadata menu from the community plugins setting tab, retry and check the console again?

**Comment by Asetnozama** [comment]
After disabling and enabling no errors anymore in the console, but the problem is still there. I can confirm if in a page with a fileclass opening the view with the command palette gives the table view list with all the files. But if I'm on a different page, so a page without a fileclass and than open the command palette, select a fileclass view, it opens the view, but there are no files listed.

**Comment by mdelobelle** [comment]
Ok! i've managed to reproduce this.
I've pushed a new version to fix that. can you try it?

**Comment by Asetnozama** [comment]
It's fixed!! Thanks
