### ISSUE TITLE
Question about dataviewjs modify

### ISSUE THREAD

**Issue by ChitaGideon** [mdelobelle/metadatamenu#196]
I define a fileclass like this:
```
fileClass:: {"type":"Select","options":{"valuesList":{"1":"objective","2":"obj","3":"objNote"},"sourceType":"ValuesFromDVQuery","valuesListNotePath":"","valuesFromDVQuery":"dv.pages('\"meta/fileClass\"').map(p => p.name)"}}
aliases:: {"type":"Input","options":{}}
```
and trying to modify file use dataviewjs like this:
```dataviewjs
const {fieldModifier:f} = this.app.plugins.plugins["metadata-menu"].api;
dv.table(["name","fileClass"],
await Promise.all(await dv.pages('"objective"').map(async p => [p.file.link, await f(dv,p,"fileClass")])
));
```
list cannot display and error show:
![QQ20221127-085857-HD](https://user-images.githubusercontent.com/1167456/204114560-cbb7c379-5b17-4402-be9d-6fb89ae2de7b.gif)
Error message :
```
plugin:metadata-menu:1938 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at eval (plugin:metadata-menu:1938:72)
    at Array.filter (<anonymous>)
    at Proxy.where (plugin:dataview:9416:39)
    at Proxy.filter (plugin:dataview:9419:21)
    at ValueSuggestModal.getSuggestions (plugin:metadata-menu:1938:56)
    at ValueSuggestModal.t.updateSuggestions (app.js:1:1560528)
    at ValueSuggestModal.t.onOpen (app.js:1:1560370)
    at ValueSuggestModal.eval (plugin:metadata-menu:1836:63)
    at Generator.next (<anonymous>)
    at eval (plugin:metadata-menu:60:61)
```
Anything wrong I did here, or it is just a bug?

**Comment by ChitaGideon** [comment]
I think I work it out ,the hint was really puzzled me

**Comment by njwander** [comment]
> I think I work it out ,the hint was really puzzled me

how you work it out? I meet the same error!

**Comment by ChitaGideon** [comment]
> > I think I work it out ,the hint was really puzzled me
> 
> how you work it out? I meet the same error!

try a different function for `Values source type`
