### ISSUE TITLE
[Obsidian 1.5 error] — Metadata menu autosuggest within tables freezes the entire app

### ISSUE THREAD

**Issue by rushikb** [mdelobelle/metadatamenu#438]
Flagging potential issue I'm seeing in the just-released Obsidian catalyst 1.5 — selecting autosuggest menu option causes the entire vault to freeze, 

Error: 
```
app.js:1 RangeError: Field is not present in this state
    at e.field (app.js:1:338560)
    at import_view.ViewPlugin.fromClass.decorations.buildDecorations (plugin:metadata-menu:12029:33)
    at new import_view.ViewPlugin.fromClass.decorations (plugin:metadata-menu:12015:31)
    at e.create (app.js:1:394529)
    at e.update (app.js:1:394959)
    at e.setState (app.js:1:495426)
    at t.clear (app.js:1:1353306)
    at t [as constructor] (app.js:1:1350205)
    at new t (app.js:1:1370839)
    at t.editTableCell (app.js:1:1366505)
    at t.receiveCellFocus (app.js:1:1286574)
    at t.setCellFocus (app.js:1:1286362)
    at app.js:1:1278063
    
```
  
![CleanShot 2023-11-21 at 14 53 49](https://github.com/mdelobelle/metadatamenu/assets/6484525/7f23502d-6193-4df2-83f1-c3e670df5a73)

**Comment by mdelobelle** [comment]
Thanks I have a fix.
inline fields aren't usable in tables right now: dataview is parsing the full line after the `::` (not stopping after the first next `|` )
I will disable the autosuggest in tables in the next beta release

**Comment by mdelobelle** [comment]
you can test this version https://github.com/mdelobelle/metadatamenu/releases/tag/0.6.0-beta-9
