### ISSUE TITLE
Cannot read properties of null (reading 'path')

### ISSUE THREAD

**Issue by quantumfate** [mdelobelle/metadatamenu#447]
The successor and same problem of #439 but with a different error message. Metadata-Menu Version 0.6.1
```
app.js:1 Uncaught TypeError: Cannot read properties of null (reading 'path')
    at IndexStatus.checkForUpdate (plugin:metadata-menu:22223:74)
    at eval (plugin:metadata-menu:23892:28)
    at e.tryTrigger (app.js:1:695499)
    at e.trigger (app.js:1:695432)
    at t.trigger (app.js:1:2028169)
    at t.activeLeafEvents (app.js:1:2014065)
    at l (app.js:1:254406)
    at c (app.js:1:254522)
```

**Comment by quantumfate** [comment]
After the update the window still crashes but this time without an error.
