### ISSUE TITLE
File link broken when Wikilinks is disabled

### ISSUE THREAD

**Issue by leeloo-1337** [mdelobelle/metadatamenu#720]
When you disable "Use Wikilinks" option under "Files and links", you can no longer use File field becase nothing is added upon click.

**Comment by Xananax** [comment]
I have a workaround! Using the regular "Multi" field type.

in the "Values Source Type", select "Values returned from a dataview query"
Then, in the "dataview function" field, enter something like this:
```js
dv.pages('"people"')
  .where(p => p.object_type == "person")
  .map(p => `'[${p.name}](${p.file.path})'`)
```
In my case, I'm selecting specific pages, but if you wanted just all the pages in your vault, you could do:
```js
dv.pages('""')
.map(p => `'[${p.file.name}](${p.file.path})'`)
```

You _must_ single quote the string. If you don't, you'll get:

```
app.js:1 Uncaught (in promise) YAMLParseError: Unexpected scalar at node end at line 1, column 11:

[test]("taxonomy/tag/test.md")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at constructor.onError (app.js:1:1081077)
    at _w (app.js:1:1064330)
    at app.js:1:1070263
    at Yw (app.js:1:1070426)
    at app.js:1:1079005
    at rk (app.js:1:1079549)
    at app.js:1:1082667
    at lk.next (app.js:1:1082810)
    at next (<anonymous>)
    at lk.compose (app.js:1:1081923)
```

------


I use double quotes like so:
```
dv.pages('"taxonomy/tag"')
.map(p => `"[${p.file.name}](${p.file.path})"`)
```

Then the YAML breaks and my links are double-quoted:

```yaml
tags:
  - ""[physics](taxonomy/tag/physics.md)""
```

So using single quotes is the only solution. It isn't pretty, as it quotes every link:

<img width="481" height="58" alt="Image" src="https://github.com/user-attachments/assets/5b2e9cef-2e04-465e-831d-1c9512b4bc4c" />

And the list is hard to read:

<img width="688" height="556" alt="Image" src="https://github.com/user-attachments/assets/05f0c669-e98b-45b4-ae8b-798f6b60be6d" />

But at least it _nominally_ works and also maybe gets us closer to understanding where the problem is. Somewhere, somehow, Obsidian thinks the link should not be parsed as a string.

PS: I tried escaping my strings like so:

```
.map(p => `\\[${p.file.name}\\]\\(${p.file.path}\\)`)
```
but that prints the string with the escape characters. Using only one `\` doesn't change anything.
