### ISSUE TITLE
Evaluation Error: `TypeError: item.trim is not a function`

### ISSUE THREAD

**Issue by AsfixGroup** [mdelobelle/metadatamenu#721]
**Description:** While using the `metadata-menu` plugin alongside `dataview`, the following error occurred:

```
TypeError: item.trim is not a function
    at eval (plugin:metadata-menu:3943:35)
    at Array.forEach ()
    at createDvField5 (plugin:metadata-menu:3939:26)
    at createDvField23 (plugin:metadata-menu:20322:14)
    at fieldModifier (plugin:metadata-menu:24586:9)
    at eval (plugin:metadata-menu:24836:41)
    at eval (eval at  (plugin:dataview), :51:73)
    at Array.map ()
    at eval (eval at  (plugin:dataview), :45:6)
    at DataviewInlineApi.eval (plugin:dataview:18885:16)
    at evalInContext (plugin:dataview:18886:7)
    at asyncEvalInContext (plugin:dataview:18896:32)
    at DataviewJSRenderer.render (plugin:dataview:18922:19)
    at maybeRefresh (plugin:dataview:18476:18)
    at e.tryTrigger (app://obsidian.md/app.js:1:723190)
    at e.trigger (app://obsidian.md/app.js:1:723123)
    at t.trigger (app://obsidian.md/app.js:1:2283688)
    at DataviewPlugin.eval (plugin:dataview:20349:76)
    at l (app://obsidian.md/app.js:1:522936)
    at c (app://obsidian.md/app.js:1:523052)






```

**Steps to Reproduce:**

1.  Use the `metadata-menu` plugin in combination with `dataview`.
2.  Perform an action (e.g., calling a function or script using dataview inline API) that triggers the field creation.
3.  The error is thrown.

**Expected Behavior:** The action should execute without errors, and fields should be processed as expected.

**Actual Behavior:** The error message indicates that `item.trim` is not a function, leading to a TypeError and breaking the functionality.

**Environment:**

*   OS: MacOS

**Comment by SourignaSimmalavong** [comment]
Hello,

I had the same issue on Windows. On my side, this happened because I recreated a field with a different type in my fileclass but forgot to update some notes having that fileclass and that field (trying to set an Object value to a field that is now a Multi does not work well ...).

I implemented a workaround in my fork (https://github.com/SourignaSimmalavong/metadatamenu). The `item.trim is not a function` error is not displayed anymore, and basically, the fields values from rows with errors won't appear and thus won't be editable. You can also see the filename, the field and its erroneous value in the console.

Hope it helps!

Cheers!

**Comment by HippyCraig** [comment]
Im having the same issue with my vault and it only seems to be effecting the one class.  I deleted the file class, and recreated with the exact same values.  And I still get presented with Error below.  If I create this same class with a different name but the rest of them the same then I don't get this error at all.


![Image](https://github.com/user-attachments/assets/1d4b3ae7-971c-4890-993a-b9ea02a5773e)

**Comment by HippyCraig** [comment]
Strange thing I duplicated the setting as a new name with a file name longer than the original of 3 char.  Once I compared the two they both had the same values except for the file name.  Deleted the old and used the new and everything is fine for now, but its not clear why a short file name, based on my experiment, had caused this.
